In [33]:
# Esercizio 1
import numpy as np
# Genera numeri interi compresi tra 10 e 49
arr = np.arange(10,50)
print(arr)
print(arr.dtype)
arr2 = arr.astype(float)
print(arr2.dtype)
print(arr2.shape)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
int32
float64
(40,)


In [34]:
# Esercizio 2

arr = np.random.randint(10,51, size = 20)
arr


array([24, 33, 22, 13, 20, 16, 38, 21, 20, 22, 28, 17, 36, 35, 34, 39, 14,
       48, 17, 12])

In [39]:
print("Primi 10 numeri ",arr[:10])
print("Ultimi 5 numeri",arr[-5:])
print("Numeri con indice compreso tra 5 e 15 (escluso)",arr[5:15])
print("Lista a step di 3",arr[2::3])
arr2 = arr.copy()
arr2[5:10] = 99
print("Array con 99 negli indici compresi tra 5 e 10",arr2)

Primi 10 numeri  [24 33 22 13 20 16 38 21 20 22]
Ultimi 5 numeri [39 14 48 17 12]
Numeri con indice compreso tra 5 e 15 (escluso) [16 38 21 20 22 28 17 36 35 34]
Lista a step di 3 [22 16 20 17 34 48]
Array con 99 negli indici compresi tra 5 e 10 [24 33 22 13 20 99 99 99 99 99 28 17 36 35 34 39 14 48 17 12]


In [40]:
print(arr)
print(arr2)

[24 33 22 13 20 16 38 21 20 22 28 17 36 35 34 39 14 48 17 12]
[24 33 22 13 20 99 99 99 99 99 28 17 36 35 34 39 14 48 17 12]


In [46]:
# Esercizio 3

mat1 = np.linspace(0, 1, 12)
mat1 = mat1.reshape(3,4)

In [48]:
mat2= np.random.rand(3,4)
mat_tot = mat1 + mat2 
mat_tot

array([[0.81569   , 0.28541837, 0.60937367, 0.61120658],
       [0.60621701, 0.51069873, 0.95278394, 1.19548308],
       [0.78041076, 1.00528746, 1.7058187 , 1.59518812]])