In [33]:
# Esercizio 1
import numpy as np
# Genera numeri interi compresi tra 10 e 49
arr = np.arange(10,50)
print(arr)
print(arr.dtype)
arr2 = arr.astype(float)
print(arr2.dtype)
print(arr2.shape)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
int32
float64
(40,)


In [34]:
# Esercizio 2

arr = np.random.randint(10,51, size = 20)
arr


array([24, 33, 22, 13, 20, 16, 38, 21, 20, 22, 28, 17, 36, 35, 34, 39, 14,
       48, 17, 12])

In [39]:
print("Primi 10 numeri ",arr[:10])
print("Ultimi 5 numeri",arr[-5:])
print("Numeri con indice compreso tra 5 e 15 (escluso)",arr[5:15])
print("Lista a step di 3",arr[2::3])
arr2 = arr.copy()
arr2[5:10] = 99
print("Array con 99 negli indici compresi tra 5 e 10",arr2)

Primi 10 numeri  [24 33 22 13 20 16 38 21 20 22]
Ultimi 5 numeri [39 14 48 17 12]
Numeri con indice compreso tra 5 e 15 (escluso) [16 38 21 20 22 28 17 36 35 34]
Lista a step di 3 [22 16 20 17 34 48]
Array con 99 negli indici compresi tra 5 e 10 [24 33 22 13 20 99 99 99 99 99 28 17 36 35 34 39 14 48 17 12]


In [40]:
print(arr)
print(arr2)

[24 33 22 13 20 16 38 21 20 22 28 17 36 35 34 39 14 48 17 12]
[24 33 22 13 20 99 99 99 99 99 28 17 36 35 34 39 14 48 17 12]


In [46]:
# Esercizio 3
mat1 = np.linspace(0, 1, 12)
mat1 = mat1.reshape(3,4)

In [48]:
mat2= np.random.rand(3,4)
mat_tot = mat1 + mat2 
mat_tot

array([[0.81569   , 0.28541837, 0.60937367, 0.61120658],
       [0.60621701, 0.51069873, 0.95278394, 1.19548308],
       [0.78041076, 1.00528746, 1.7058187 , 1.59518812]])

In [60]:
print(np.linspace(0, 1, 12).reshape(3,4) + np.random.rand(3,4))

[[0.56446817 0.73475632 0.9440695  1.12149328]
 [0.45107367 0.63145311 0.66977409 1.55236509]
 [0.97434439 1.11281305 1.34840883 1.86449062]]


In [63]:
# Esercizio 4

arr = np.linspace(0,10,50)
arr_casuale = np.random.rand(50)
arr_somma = arr + arr_casuale
totale = sum(arr_somma)
totale_magg5 = arr_somma[arr_somma > 5].sum()

In [64]:
print("Array equidistante",arr)
print("Array casuale",arr_casuale)
print("array somma", arr_somma)
print("somma totale ultimo array",totale)
print("somma dove array > 5", totale_magg5)

Array equidistante [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
Array casuale [0.01503298 0.61087162 0.10717691 0.41808802 0.78238952 0.85334517
 0.75017988 0.88973383 0.15021057 0.64864517 0.05721603 0.0460849
 0.90484122 0.89168529 0.41594131 0.39768682 0.07480366 0.90205565
 0.21918482 0.94033816 0.16449834 0.6325432  0.24242696 0.0936782
 0.71563154 0.28573579 0.55967998 0.53679194 0.5285883  0.40261281
 0.28225398 0.83579581 0